config/routes.rb
Rails.application.routes.draw do
  root "pictures#index"
  resource :users, only: %i(create new)
  resource :sessions, only: %i(create new destroy)
  resources :pictures

  resources :likes, :only => [:create]
  # resources :comments
  post '/comments/:id', to: 'comments#create'
  get '/comments/:id', to: 'comments#index', as: :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :comments
end





# class Picture < ApplicationRecord
# <<<<<<< merge-with-pk
#   belongs_to :user
# =======
#   has_many :comments
#   belongs_to :user

# >>>>>>> master
# end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  # before_action :require_logged_in
  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end
  def imgur
        @pictures = Picture.all
  end
  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    # puts "*****picture create********"
    @picture = Picture.new(picture_params)
    @picture.user = current_user

    respond_to do |format|
      if @picture.save
        format.html { redirect_to pictures_path, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:title, :url)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<div class="textcontainer">
<%= form_with(model: picture, local: true) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<br>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :picture_title %>
  </div>
<br>
  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :picture_url %>
  </div>
<br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/imgur.html.erb
<body>



<div class="navbar">
  <div class="leftbar">

      <div class="logo">Photogur</div>
      <div class="pulldown"><i class="fas fa-chevron-down"></i></div>
      <div class="newpost"></div>

  </div>

  <div class="rightbar">
    <!-- <i class="fas fa-search"></i> -->
    <div class="nextright">
      Sign Up
    </div>
    <div class="navright">
      <% if current_user %>
        Signed in as <%= current_user.username %>. <%= link_to "Log out", sessions_path("current"), :method => :delete %>
      <% else %>
        <%= link_to "Log in", new_sessions_path %> or <%= link_to "Sign up", new_users_path %>
      <% end %>    </div>

  </div>
</div>



  <div class="leftpane">
  </div>
  <div class="textcontainer">
    <p>
    The most random collection of stock photos, unsorted.<br>
    <span>some pics we'll call popular, just because.</span>
    </p>
  </div>

<div class="mainarea">



    <div class="grid-tl">
        <%= image_tag(@pictures.first.url )%>
    </div>
    <div class="grid-tlc">

    </div>
    <div class="grid-tc">

    </div>
    <div class="grid-trc">

    </div>
    <div class="grid-tr">

    </div>
    <div class="grid-ml">

    </div>
    <div class="grid-mlc">

    </div>
    <div class="grid-mc">

    </div>
    <div class="grid-mrc">

    </div>
    <div class="grid-mr">

    </div>
    <div class="grid-bl">

    </div>
    <div class="grid-blc">

    </div>
    <div class="grid-bc">

    </div>
    <div class="grid-brc">

    </div>
    <div class="grid-br">

    </div>

</div>

<div class="rightpane">
</div>

</div>
</body>

app/views/pictures/index.html.erb
<!-- <div class="imgur">
<div class="navbar">
<div class="leftbar">
<div class="logo"><%= link_to 'PetShow', pictures_path %></div>
<div class="pulldown"><i class="fas fa-chevron-down"></i></div>
<div class="newpost"></div>
<div class="newpost">
<% if current_user %>
<%= link_to 'New Picture', new_picture_path %>
<% end %>
</div>
</div>


<div class="rightbar">
<div class="magnify">
<i class="fas fa-search"></i>
</div>
<div class="nextright">
<p class="userinfo">
<% if current_user %>
Signed in as <%= current_user.username %>. <%= link_to "Log out", sessions_path("current"), :method => :delete %>
<% else %>
<%= link_to "Log in", new_sessions_path %> or <%= link_to "Sign up", new_users_path %>
<% end %>
</p>
</div>

</div>
</div>


<div class="leftpane">
</div> -->
<div class="textcontainer">
  <p class="greeting">
    PetShow - Show off your pet!<br>
    <span>A collection of our Pets!  </span><i class="fas fa-paw"></i>

  </p>
</div>

<div class="mainarea">
  <% @pictures.each do |picture| %>
  <div class="grid">

    <%= image_tag(picture.url, width:"100%", height: "50%" )%>
    <span class="picture_title">
      <%= picture.title %> </br>
      <% if current_user %>
      <i class="fas fa-paw"></i>
      <!-- <%= link_to 'Show', picture %> -->
      <%= link_to 'Comments', comments_path(picture)%></br>
      <%= link_to 'Edit', edit_picture_path(picture) %>
      <%= link_to 'Remove', picture, method: :delete, data: { confirm: 'Are you sure?' } %></br>


      <!-- <%= button_to "Like", likes_path, params: {user_id: current_user.id, picture_id: picture.id}, remote: true%> -->
      <!-- <form  class="button_to">
      <div><input class="my_class" id=picture.id  value="Like" type="submit" /></div>
    </form> -->
    <% end %>

  </div>
  <% end %>
</div>
</span>

<!-- <div class="rightpane">
</div>

</div>
</div> -->

app/views/pictures/new.html.erb
<div class="textcontainer">
  <h1>New Picture</h1>
<br>
<%= render 'form', picture: @picture %>
<br>
<%= link_to 'Back', pictures_path %>
</div>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @picture.title %>
</p>
<p>
  <%= image_tag @picture.url %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>