config/routes.rb
Rails.application.routes.draw do
  root "pictures#index"
  resource :users, only: %i(create new)
  resource :sessions, only: %i(create new destroy)
  resources :pictures

  resources :likes, :only => [:create]
  # resources :comments
  post '/comments/:id', to: 'comments#create'
  get '/comments/:id', to: 'comments#index', as: :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetShow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" type="text/css" rel="stylesheet">
    <link rel="shortcut icon" href="/assets/favicon.png">
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i' %>

  </head>

  <body>
  <div class="imgur">
    <div class="navbar">
      <div class="leftbar">
        <div class="logo"><%= link_to 'PetShow', pictures_path %></div>
        <div class="newpost">
          <% if current_user %>
          <%= link_to 'New Picture', new_picture_path %>
          <% end %>
        </div>
      </div>


      <div class="rightbar">
        <div class="magnify">
          <i class="fas fa-search"></i>
        </div>
        <div class="nextright">
          <p class="userinfo">
            <% if current_user %>
            Signed in as <%= current_user.username %>. <%= link_to "Log out", sessions_path("current"), :method => :delete %>
            <% else %>
            <%= link_to "Log in", new_sessions_path %> or <%= link_to "Sign up", new_users_path %>
            <% end %>
          </p>
        </div>

      </div>
    </div>
    <div class="leftpane">
    </div>
    <%= yield %>
    <div class="rightpane">
    </div>

    </div>
    </div>
  </body>
</html>